### ISSUE TITLE
How to use this plugin in android

### ISSUE THREAD

**Issue by Tetsukick** [krokyze/FitKit#47] opened 2020-05-17 19:28 UTC
I really don't know how to make it work in android. I do enable the Fitness API and also obtain an OAuth 2.0 client ID. But the ID is nowhere to use. There is a prompt for which Google account to use, but then just silent disappear, then no error, await FitKit.requestPermissions(DataType.values) just return false.

**Comment by vvicenteboo** [comment] 2020-06-02 13:47
same issue here, any solution?, for me requestPermissions only works on dev but crashes on release apk

**Comment by krokyze** [comment] 2020-06-13 19:27
Duplicate of #45

**Closed as completed by krokyze** 2020-06-13 19:27 UTC
