### ISSUE TITLE
Example: PlatformException

### ISSUE THREAD

**Issue by manusmarthome** [krokyze/FitKit#50] opened 2020-05-30 21:27 UTC
Hi, I am new to Flutter and Google Fit integration. I tried following the example provided and I am seeing 
Result: realdAll: PlatformException(FitKit, type stand_time is not supported, null)

Can someone help me with this?

**Comment by krokyze** [comment] 2020-06-13 19:04
Duplicate of #36

**Closed as completed by krokyze** 2020-06-13 19:04 UTC
