### ISSUE TITLE
how to get current permission status 

### ISSUE THREAD

**Issue by pkc1672** [krokyze/FitKit#15] opened 2019-08-14 07:36 UTC
I need to get current status at Fitness 
because need activate permission request button when permission canceled from outside .
so, how can I get that?

**Comment by krokyze** [comment] 2019-08-20 20:40
Hey, so this would work as expected only on Android GoogleFit, because iOS HealthKit in case user denies access still returns success. You can read more about this here: https://stackoverflow.com/a/56937166

In case your still interested, respond here and I will add it as a feature request.

**Comment by krokyze** [comment] 2019-11-25 21:40
Duplicate of #12

**Closed as completed by krokyze** 2019-11-25 21:40 UTC

**Comment by nongtiny** [comment] 2021-01-14 15:36
I have a hacky way to check this.

We can check from the last year's read data. Health(iOS) still collects last year's records. So, if it returns an empty list then the permission is false, else it will be true.
