### ISSUE TITLE
Request of GoogleSignIn.hasPermissions

### ISSUE THREAD

**Issue by hukusuke1007** [krokyze/FitKit#24] opened 2019-10-19 04:17 UTC
I hope support to hasPermissions API.

```
GoogleSignIn.hasPermissions(GoogleSignIn.getLastSignedInAccount(this), fitnessOptions)
```

How to use.

```
final hasPermissions = await FitKit.hasPermissions();
if (hasPermissions) {
  // read.
} else {
  // requestPermissions 
}
```

**Comment by krokyze** [comment] 2019-11-25 21:38
Duplicate of #12

**Closed as completed by krokyze** 2019-11-25 21:38 UTC
